// NOTE: This is supposed to fail.

func wrong_ret_ty1() {
	return "";
}

func wrong_ret_ty2(): str {}

func main() {

}
